# Generated by Django 4.1 on 2022-08-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'Dolars'), ('MXN', 'Mexican pesos'), ('COP', 'Colombian pesos')], default='USD', error_messages={'choices': 'Only USD, MXN or COP can be passed as currency.'}, help_text='Options for currency are the following 3: USD, MXN or COP', max_length=3, verbose_name='Currency used in the price')),
                ('location', models.CharField(error_messages={'unique': 'A room with that location already exists.'}, help_text='Floor number and room letter separated by a hyphen. Ex: 3-B', max_length=3, unique=True, verbose_name='Location')),
                ('price_per_night', models.DecimalField(decimal_places=2, error_messages={'max_digits': 'Room price can not be more expensive than $9,999.99'}, help_text='Enter this room price per night (it can not be more expensive than $9,999.99). Ex: 120.00', max_digits=6, verbose_name='Price Per Night')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is this room currently available?')),
            ],
        ),
    ]
