# Generated by Django 4.1 on 2022-08-28 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PNDG', 'Pending'), ('PAID', 'Paid'), ('RMVD', 'Removed')], default='PNDG', error_messages={'choices': "Only 'PNDG' for pending status, 'PAID' for paid status or 'RMVD' for removed status can be passed as status."}, help_text="Options for currency are the following 3: 'PNDG' for pending status, 'PAID' for paid status or 'RMVD' for removed status", max_length=4, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('EFF', 'Effective cash'), ('DBT', 'Debit card'), ('CDT', 'Credit card')], error_messages={'choices': "Only 'EFF' for effective cash, 'DBT' for debit card or 'CDT' for credit card can be passed as payment method."}, help_text="Options for payment method are the following 3: 'EFF' for effective cash, 'DBT' for debit card or 'CDT' for credit card", max_length=3, verbose_name='Payment method')),
                ('uuid', models.UUIDField(default=uuid.UUID('1153264f-6f60-4288-a4b4-653028210f02'), editable=False, unique=True)),
                ('days_of_stay', models.IntegerField(verbose_name='Days of Stay')),
                ('total_price', models.CharField(blank=True, help_text='You can leave this field blank, it will be self-calculated', max_length=16, verbose_name='Total price')),
                ('room', models.ForeignKey(help_text='Pass here room room ID', on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
