# Generated by Django 4.1 on 2022-08-28 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b2d4b8f4-40c8-4f30-968b-cf00771d981a'), editable=False, unique=True),
        ),
    ]
