# Generated by Django 4.0.6 on 2022-08-29 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PNDG', 'Pending'), ('PAID', 'Paid'), ('RMVD', 'Removed')], default='PNDG', error_messages={'choices': "Only 'PNDG' for pending status, 'PAID' for paid status or 'RMVD' for removed status can be passed as status."}, help_text="Options for status are the following 3: 'PNDG' for pending status, 'PAID' for paid status or 'RMVD' for removed status", max_length=4, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('eef3f7ff-0edf-42c2-bc28-25433e4355ae'), editable=False, unique=True),
        ),
    ]
