# Generated by Django 4.2.4 on 2023-08-10 04:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_status_alter_reservation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('90f28371-ba0c-4046-8c43-72cf4ba6307b'), editable=False, unique=True),
        ),
    ]
